//=========================================================
// src/carrillon_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
	CKCON0|=1<<2;
	TCON|=TCON_TR0__BMASK;

}

#define PAUSE (0)
#define C4 (1)
#define CS4 (2) // dièse
#define DB4 (2) // bémol
#define D4 (3)
#define DS4 (4)
#define EB4 (4)
#define E4 (5)
#define F4 (6)
#define FS4 (7)
#define GB4 (7)
#define G4 (8)
#define GS4 (9)
#define AB4 (9)
#define A4 (10)
#define AS4 (11)
#define BB4 (11)
#define B4 (12)
#define C5 (13)
#define CS5 (14)
#define DB5 (14)
#define D5 (15)
#define DS5 (16)
#define EB5 (16)
#define E5 (17)
#define F5 (18)
#define FS5 (19)
#define GB5 (19)
#define G5 (20)
#define GS5 (21)
#define AB5 (21)
#define A5 (22)
#define AS5 (23)
#define BB5 (23)
#define B5 (24)

// times
#define WHOLE  (64)
#define HALF  (32)
#define QUARTER  (16)
#define HEIGHTH (8)
#define SIXTEENTH (4)


unsigned char code scale[25]={
		0,  // PAUSE
		244, // C4
		230, // C#4
		217, // D4
		205, // D#4
		194, // E4
		183, // F4
		172, // F#4
		163, // G4
		154, // G#4
		145, // A4
		137, // A#4
		129, // B4
		122, // C5
		115, // C#5
		109, // D5
		102, // D#5
		97,  // E5
		91,  // F5
		86,  // F#5
		81,  // G5
		77,  // G#5
		73,  //  A5
		68,  // A#5
		65,   // B5

};

#define ODE_TEMPO (20)
#define ODE_SCORE (62)
#define ODE_LEN (ODE_SCORE*2+2)
unsigned char code ode_joie[ODE_LEN]={
		ODE_LEN,ODE_TEMPO,
		A4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		C5,QUARTER,
		C5,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		A4,QUARTER+HEIGHTH,
		G4,HEIGHTH,
		G4,HALF,
		A4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		C5,QUARTER,
		C5,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		G4,QUARTER+HEIGHTH,
		F4,HEIGHTH,
		F4,HALF,
		G4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,HEIGHTH,
		AS4,HEIGHTH,
		A4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,HEIGHTH,
		AS4,HEIGHTH,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		C4,HALF,
		A4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		C5,QUARTER,
		C5,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		G4,QUARTER+HEIGHTH,
		F4,HEIGHTH,
		F4,HALF
};

#define CLAIRE_F_TEMPO (20)
#define CLAIRE_F_SCORE (41)
#define CLAIRE_F_LEN (CLAIRE_F_SCORE*2+2)
unsigned char code claire_fontaine[CLAIRE_F_LEN]={
   CLAIRE_F_LEN,CLAIRE_F_TEMPO,
   // première mesure
   G4,HALF,
   G4,QUARTER,
   B4,QUARTER,
   B4,QUARTER,
   A4,QUARTER,
   B4,QUARTER,
   G4,QUARTER,
   G4,HALF,
   G4,QUARTER,
   B4,QUARTER,
   B4,QUARTER,
   A4,QUARTER,
   B4,HALF,
   // deuxième mesure
   B4,HALF,
   B4,QUARTER,
   A4,QUARTER,
   G4,QUARTER,
   B4,QUARTER,
   D5,QUARTER,
   B4,QUARTER,
   D5,HALF,
   D5,QUARTER,
   B4,QUARTER,
   G4,QUARTER,
   B4,QUARTER,
   A4,HALF,
   // troisième mesure
   G4,HALF,
   G4,QUARTER,
   B4,QUARTER,
   B4,QUARTER,
   A4,HEIGHTH,
   G4,HEIGHTH,
   B4,QUARTER,
   G4,QUARTER,
   B4,HALF,
   B4,QUARTER,
   A4,HEIGHTH,
   G4,HEIGHTH,
   B4,QUARTER,
   A4,QUARTER,
   G4,HALF
};

#define FRERE_J_TEMPO (20)
#define FRERE_J_SCORE (32)
#define FRERE_J_LEN (FRERE_J_SCORE*2+2)
unsigned char code frere_jacques[FRERE_J_LEN]={
		FRERE_J_LEN,FRERE_J_TEMPO,
		F4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		F4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		C5,HALF,
		A4,QUARTER,
		AS4,QUARTER,
		C5,HALF,
		C5,HEIGHTH+SIXTEENTH,
		D5,SIXTEENTH,
		C5,HEIGHTH,
		AS4,HEIGHTH,
		A4,QUARTER,
		F4,QUARTER,
		C5,HEIGHTH+SIXTEENTH,
		D5,SIXTEENTH,
		C5,HEIGHTH,
		AS4,HEIGHTH,
		A4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		C4,QUARTER,
		F4,HALF,
		F4,QUARTER,
		C4,QUARTER,
		F4,HALF
};

#define MELODIA_TEMPO (20)
#define MELODIA_SCORE (43)
#define MELODIA_LEN (MELODIA_SCORE*2+2)
unsigned char code melodia[MELODIA_LEN]={
		MELODIA_LEN,MELODIA_TEMPO,
		A4,QUARTER,
		A4,QUARTER,
		A4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		E4,QUARTER,
		D4,QUARTER,
		D4,QUARTER,
		F4,QUARTER,
		A4,QUARTER,
		D5,QUARTER,
		D5,QUARTER,
		D5,QUARTER,
		D5,QUARTER,
		C5,QUARTER,
		AS4,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		G4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		CS5,QUARTER,
		AS4,QUARTER,
		A4,QUARTER,
		A4,QUARTER,
		G4,QUARTER,
		F4,QUARTER,
		F4,QUARTER,
		E4,QUARTER,
		D4,QUARTER,
		E4,QUARTER,
		E4,QUARTER,
		E4,QUARTER,
		E4,QUARTER,
		F4,QUARTER,
		E4,QUARTER,
		D4,HALF+QUARTER
};

#define TUNES_COUNT (4)
unsigned char code  *tunes_list[TUNES_COUNT]={
		ode_joie,
		claire_fontaine,
		frere_jacques,
		melodia
};



// pause in milliseconds
void pause(unsigned int msec){
#define MSEC (65408)

	TL1=MSEC&0xff;
	TH1=MSEC>>8;
	TCON_TF1=0;
	TCON_TR1=1;
	while (msec){
		while (!TCON_TF1);
		msec--;
		TL1=MSEC&0xff;
		TH1=MSEC>>8;
		TCON_TF1=0;
	}
	TCON_TR1=0;
}

void tone(unsigned char tone,unsigned int time){
	PCA0CPH0=scale[tone];
	P1MDOUT|=P1MDOUT_B1__PUSH_PULL;
	P1_B1=1;
	pause(40);
	P1MDOUT&=~P1MDOUT_B1__PUSH_PULL;
    pause(time);
}

void music_box(unsigned char code *list){
	unsigned char n,i,length,tempo;

	length=list[0];
	tempo=list[1];
	PCA0CN0|=PCA0CN0_CR__RUN;
	for (i=2;i<length;i+=2){
		n=list[i];
		P0|=0x1f;
		P0&=~n;
		if (!n){
			pause(tempo*list[i+1]+40);
		}else{
			tone(n,tempo*list[i+1]);
		}
	}
	PCA0CN0&=~PCA0CN0_CR__RUN;
}

#define BTN_DOWN (0)
#define BTN_UP  (1)
// attend que le bouton soie
// dans l'état demandé.
void wait_button(char state){
	char count;
	count=0;
	while (count<10){
		pause(1);
		if (state==P1_B2){
			count++;
		}else{
			count=0;
		}
	}
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
	unsigned char i,mode, prev;
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();

  i=0;
  prev=0;
  mode=P1_B3;
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$
	  wait_button(BTN_DOWN);
	  if (mode){
		  do{
			 // i=random(8)%TUNES_COUNT;
			  i=TL0%TUNES_COUNT;
		  }while (i==prev);
	  }else{
		  i++;
		  i%=TUNES_COUNT;
	  }
	  P0|=0xe0;
	  P0&=~(i<<5);
	  music_box(tunes_list[i]);
	  P0=0xff;
	  prev=i;
	  wait_button(BTN_UP);
  }                             
}
